<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1ak6qbq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1ak6qbq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1ak6qbq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1ak6qbq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1ak6qbq\appDevDebugProjectContainer(array(
    'container.build_hash' => '1ak6qbq',
    'container.build_id' => '4ffe5935',
    'container.build_time' => 1534060341,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1ak6qbq');
