<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPvz4mfb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPvz4mfb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPvz4mfb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPvz4mfb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPvz4mfb\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pvz4mfb',
    'container.build_id' => '39a46625',
    'container.build_time' => 1532528109,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPvz4mfb');
